### Dataset: Balance Commerciale

In [3]:
import pandas as pd
balance_commerciale_df = pd.read_excel('/content/datasets2/final_balance_commerciale_data.xlsx')
display(balance_commerciale_df.head())

        date  Balance commerciale
0 2015-01-01           -12002.561
1 2016-01-01           -12601.188
2 2017-01-01           -15594.965
3 2018-01-01           -19022.948
4 2019-01-01           -19436.200

### Filtering `balance_commerciale_df`

In [10]:
balance_commerciale_df['date'] = pd.to_datetime(balance_commerciale_df['date'])
balance_commerciale_df_filtered = balance_commerciale_df[(balance_commerciale_df['date'] >= '2015-01-01') & (balance_commerciale_df['date'] <= '2026-01-01')]
display(balance_commerciale_df_filtered.head())
display(balance_commerciale_df_filtered.tail())

        date  Balance commerciale
0 2015-01-01           -12002.561
1 2016-01-01           -12601.188
2 2017-01-01           -15594.965
3 2018-01-01           -19022.948
4 2019-01-01           -19436.200

         date  Balance commerciale
6  2021-01-01             -16210.7
7  2022-01-01             -25231.4
8  2023-01-01             -17069.0
9  2024-01-01             -18927.6
10 2025-01-01             -21800.3

In [11]:
balance_commerciale_df_filtered.set_index('date', inplace=True)

In [12]:
df_daily = balance_commerciale_df_filtered.resample('D').interpolate(method='linear')

In [13]:
display(df_daily.head())
display(df_daily.tail())

            Balance commerciale
date
2015-01-01        -12002.561000
2015-01-02        -12004.201074
2015-01-03        -12005.841148
2015-01-04        -12007.481222
2015-01-05        -12009.121296

            Balance commerciale
date
2024-12-28        -21768.904372
2024-12-29        -21776.753279
2024-12-30        -21784.602186
2024-12-31        -21792.451093
2025-01-01        -21800.300000

In [18]:
df_daily = df_daily.reset_index()

In [20]:
df_daily.to_excel('balance_commerciale_daily.xlsx', index=False)